account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views 
from . import views 

urlpatterns = [

    path("login/",views.user_login,name="login"),
    path("logout/",views.user_logout,name="logout"),
    path("sign-up/",views.user_signup,name="signup"),
    path("reset_password/",auth_views.PasswordResetView.as_view(success_url="/accounts/password_reset_done/"), name="reset_password"),
    path("password_reset_done/", auth_views.PasswordResetDoneView.as_view(),name="password_reset_done"),
    path("reset_password/confirm/<uidb64>/<token>",auth_views.PasswordResetConfirmView.as_view(success_url="/accounts/reset_password_complete/"),name="password_reset_confirm"),
    path("reset_password_complete/",auth_views.PasswordResetCompleteView.as_view(),name="password_reset_complete"),
    path("password-change/",views.password_change,name="pwd_change"),
    path("show-MyProfile",views.showMyProfile,name="show_profile"),
    path("edit-MyProfile/",views.editMyProfile,name="editMyProfile"),
]

bookstore/urls.py
from django.conf import settings 
from django.conf.urls.static import static 
from django.urls import path 
from . import views 

urlpatterns = [
    path("show",views.get_all_books,name="books"),
    path("book-detail/<slug:slug>/",views.book_detail,name="book-detail"),
    path("download/<slug:slug>/",views.book_download,name="download"),
    path("upload/",views.upload_books,name="upload"),
    path("edit-book/<int:id>",views.edit_book,name="edit-book"),
    path("search",views.search_index,name='search'),

]

intern_report/urls.py
from django.contrib import admin
from django.urls import path,include 
from django.views.generic import TemplateView
from django.conf import settings 
from django.conf.urls.static import static 
from home import views 

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",views.homepage,name="homepage"),
    path("about/",views.aboutpage,name="aboutpage"),
    path("books/",include(("bookstore.urls","bookstore"),namespace="bookstore")),
    path("accounts/",include(("account.urls","account"),namespace="account")),
]
if settings.DEBUG:
     urlpatterns += static(
         settings.MEDIA_URL,
         document_root=settings.MEDIA_ROOT
     )

templates/about.html
{% extends 'base.html' %} 
{% load static %} 

{% block css %}
     <link rel="stylesheet" href="{% static 'about.css' %}" />
{% endblock %}
{% block content %} 
  
     <section class="about">
          <div class="about-img">
               <img src="{{ author.profile.profile_photo.url}}"/>
          </div>

        <div class="about-text">

               <p>
                    Hey everyone! My name is saleamlak. I am currently computer science student at Gambella University.
                    I am a computer enthuasiast. Particularly I am very intersting about:
                     <ul>
                         <li>Networking</li>
                         <li>Linux</li>
                         <li>mobile and web application development</li>
                         <li>pentesting</li>
                     </ul>

                   
               </p>
        </div>
        
     </section>

     <section id="address-container">
          <p>You can find me with the following address</p>
          <div class="address">
               <a href ="https://t.me/saleZHacker" target="__blank">
                    <img src="{% static 'telegram.png' %}" width="30px">@saleZHacker
               </a>
               <a href="mailto:saledream8@gmail.com" target="__blank">
                    <img src="{% static 'gmail.png' %}" width="30px">saledream8@gmail.com</a>
          </div>
     </section>

{% endblock %} 

templates/base.html
<!DOCTYPE html>

{% load bootstrap4 %}

{% load static %} 

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/x-icon" href="{% static 'images/logo.png' %}" />
    <title>
      {% block title %}SaleLibrary
      {% endblock %}
    </title>
   
     <link rel="stylesheet" href="{% static 'base.css' %}" >
     <script src="{% static 'mobile-menu.js' %}">

     </script>
    {% bootstrap_css %} 

    {% block css %} 
    {% endblock %} 

    {% block js %}
    {% endblock %} 
    
</head>
<body>

    <header>
        <div class="">

        </div>
        <div class="brand-nav">
            <div class="logo-container">
                <div class="header-logo">
                      <div class="logo">
                          <img src="{% static 'images/logo.png' %}" width="100px"/>
                      </div>
                      <h1> SaleLibary</h1>
                </div>
                <div class="header-account">

                  {% if request.user.is_authenticated %} 
                                      
                        <div class="logedin" 
                            {% if page == "account" %}
                              class="active"
                            {% endif %} >
                                <a href="{% url 'account:logout' %}">Logout</a>
                                <div class="profile_photo">
                                        <a href="/accounts/show-MyProfile?q={{request.user.username}}">
                                          <img src="{{request.user.profile.profile_photo.url}}" width="100%"/>   
                                        </a>
                                </div>
                                
                        </div>
                  {% else %}
                        <div class="notlogin"
                        {% if page == "account" %}
                              class="active"
                            {% endif %} >
                              <a class="signin" href="{% url 'account:login' %}">
                                  signin
                              </a>
                              <a class="signup" href="{% url 'account:signup' %}">
                                singup
                              </a>
                        </div>
                  {% endif %} 

                </div>
            </div>
            
            <nav class="nav-items-container">
                       <div class="for-mobile">
                            <div  class="common-links">
                                    <a href="{% url 'homepage' %}" 
                                    {% if page == 'home' %}
                                          class="active"
                                        {% endif %}
                                        class="nav-link">Home</a>
                                  <a href="/books/show"  {% if page == 'books' %}
                                        class="active"
                                      {% endif %}class="nav-link ">Books</a>

                                      <a href="{% url 'bookstore:upload' %}"  {% if page == 'upload' %}
                                      class="active"
                                    {% endif %}class="nav-link ">Upload book</a>

                                    <a href="{% url 'aboutpage' %}"  {% if page == 'about' %}
                                      class="active"
                                    {% endif %}class="nav-link ">About</a>
                                    
                                    
                            </div>
                        <div class="mobile-menu" data-menu="on"
                              onclick="showMenu();">
                                  <div id="top-bar">

                                   </div>
                                  <div id="middle-bar">

                                  </div>
                                  <div id="lower-bar">

                                  </div>
                        </div>
 
                      </div>
                        
                         <div id="hidden">
                            
                            <div class="mobile-category">
                                <p> Books category</p>
                              {% for cate in category %} 
 
                                  <a href="/books/show?q={{cate}}" onclick="highlight(this);"> {{cate}}</a>

                              {% endfor %}
                            </div>
                            
                        </div>
                        
            </nav>
           
        </div>
    </header>
   <main>
    <section class="main-space">
      <div>

      </div>
      <div class="bg-color">

      </div>
      <div>

      </div>
   </section>
       {% block content %} 

       {% endblock %} 
    </main>
    

</body>
</html>

templates/book-detail.html
{% extends 'base.html' %} 
{% load static %} 
{% block css %} 
<link rel="stylesheet" href="{% static 'book-detail.css' %}"/>
{% endblock %} 
{% block js %} 
    <script src="{% static 'download.js' %}">

    </script>
{% endblock %} 

{% block content %}
   <section class="main-grid">
      <div class="book-detail">
            <div class="book-container">
                    <h1>{{book.title}}</h1>
                <div>
                        <div class="book-cover">
                                <div>
                                    <img src="{{book.cover.url}}" width="100%"/>
                               
                                </div>
                                <a href="{% url 'bookstore:download' book.slug %}">                                <input type="button" value="Download"
                                onclick="download_file('{{book.slug}}');"
                                class="download-btn"/>
                                </a>
                        </div> 
                        <div class="metadata">
                             
                            <p> <span>Title:</span> {{book.title}}</p>   
                
                            <p> <span>Author:</span> {{book.author}}</p>  
                            <p> <span>Pages:</span> {{book.pages}}</p>  
                            <p> <span>Size:</span> {{book.size}}</p>  
                            <p> <span>Language:</span> {{book.language}}</p> 
                            <p> <span>Published_year:</span> {{book.published_year}}</p> 
                            <p> <span>File Type:</span> {{book.file_type}}</p> 
                        </div>
                    </div>
            </div>
           <div class="description">
                 {% if book.description != '' %}
                 <h3> book description</h3> 
                      <p>{{book.description}}</p>
                 {% endif %}
                 
           </div>
           <h4> Uploaded By: 
            <a href="/accounts/show-MyProfile?q={{book.upload_by.username}}">{{book.upload_by.username}}</a></h3>

      </div>
      
      <div class="mobile-links">
        <hr>
       
       {% if request.user == book.upload_by %} 
         <a href="{% url 'bookstore:edit-book' book.id %}">Edit this book</a>
         {% endif %}
     </div>
      
      <aside>
            <div class="books-category">
                <p>Books category</p>
                 {% for cate in category %} 
                   <a href="/books/show?q={{cate}}">{{cate}}</a>
                 {% endfor %}
      
            </div> 
            <div class="links">
                
                {% if request.user == book.upload_by %} 
                <a href="{% url 'bookstore:edit-book' book.id %}">Edit this book</a>
                {% endif %}
            </div> 
           
                
         </aside>
   </section>
   
{% endblock %}

templates/books.html
{% extends 'base.html' %} 
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'books.css' %}"/>
{% endblock %} 

{% block js %}
     <script src="{% static 'highlightcategory.js' %}">

     </script>
{% endblock %}
{% block content %}
<div class="white-title-container">
   
</div>
<section class="main-grid">
   <section class="books">
        <h1>{{bc}}</h1>
          <hr class="header-line">
          <div class="books-grid">
            {% for book in books %} 
               <div class="book-container">
                        <div class="book-cover">
                          <a href="{% url 'bookstore:book-detail' book.slug %}">
                              <img src="{{book.cover.url}}" width="150px" alt="{{book.title}}"/>
                            

                              </a>
                        </div>
                        <div class="book-metadata">
                     
                                <p><span>Title</span>:
                                  {{book.title}} </p> 
                              <p><span>Author</span>:
                                  {{book.author}} </p> 
                              
                              <p><span>pages</span>:  
                                 {{book.pages}}
                              </p>
                           
                              <p><span>size</span>: 
                                 {{book.size}}
                              </p>
                         
                            
                        </div>
                              
               </div>
               <hr class="bottom-line">
               {% empty %} 
                  <h1> No Books</h1>
               {% endfor %}
            </div>
          
   </section>
   <aside>
      <div class="books-category">
          <p>Books category</p>
          {% for cate in category %} 
 
          <a href="/books/show?q={{cate}}" onclick="highlight(this);"> {{cate}}</a>

          {% endfor %}


      </div>  
     
          
   </aside>
</section>

{% endblock %}

templates/edit-book.html
{% extends 'base.html' %} 
{% load static %} 
{% block title %}
     Edit book 
{% endblock %}

{% block css %}
   <link rel="stylesheet" href="{% static 'edit-book.css' %}"/>
{% endblock %} 

{% block content %} 
<section class="book-edit">   
       <div class="book-cover">
            <img src="{{book.cover.url }}" width="150px" />
       </div>
       <div class="form">
            <form method="post" enctype="multipart/form-data">
               {% csrf_token %}
              {% for field in form %} 
                 <div class="field">
                     <p class="label">{{field.label}}</p>
                     <p class="input">{{field}}</p>
                 </div>
              {% endfor %}
               <input type="submit" value="save"/>
            </form>
       </div>
</section>
{% endblock %}

templates/editmyprofile.html
{% extends 'base.html' %} 
{% load static %} 

{% block css %} 
      <link rel="stylesheet" href="{% static 'editmyprofile.css' %}"/>
{% endblock %}

{% block js %} 
   <script src="{% static 'editmyprofile.js' %}">
    
   </script>
{% endblock %}
{% block content %}
      <form method="post" enctype="multipart/form-data"> 
           {% csrf_token %}
            <section class="user-profile">
                <div class="profilePhoto">
                    <div class="photo">
                        <img src="{{user.profile.profile_photo.url}}"/>
                    </div>
                    {% for field in profile %} 
                    <div class="field-label">
                        <p class="input">{{field}}</p>
                        <p class="label">{{field.label}}</p>
                    </div>
                {% endfor %}
                </div>
                <div class="user">
                    {% for field in userform %} 
                    <div class="field-label">
                        <p class="input">{{field}}</p>
                        <p class="label">{{field.label}}</p>
        
                    </div>
                    {% endfor %}
                
                </div>
        
        </section>
        <input type="submit" value="save" />
   </form>
{% endblock %}  

templates/index.html
{% extends 'base.html' %} 

{% load static %} 

{% block css %} 
  <link rel="stylesheet" href="{% static 'home.css' %}"/>
{% endblock %} 

{% block js %} 
 <script src="{% static 'search.js' %}">

 </script>
{% endblock %} 

{% block content %} 

    <section class="logo-background">
        
    </section>
    <section class="section-container">
            <section>
                <h4> Your gateway to knowledge!</h4>
            </section>

            <section class="search">
                <input type="search"/>
                <input type="button" onclick="search_book();" value="search"/>
            </section>
            
            <h5 id="result">Personally Recommended</h5>
          
            <hr>
            <section class="grid-books">
                {% for book in books %}
                  <div class="grid-cover">
                      <a href="{% url 'bookstore:book-detail' book.slug %}">
                        <img src="{{book.cover.url}}" width="100%" />
                      </a>
                  </div>
                {% endfor %}
            </section>
    </section>
{% endblock %}

templates/login.html
{% extends 'base.html' %} 
{% load static %}  
 
{% block css %} 
  <link rel="stylesheet" href="{% static 'login.css' %}"/> 
{% endblock %}

{% block js %} 

{% endblock %} 

{% block content %} 
     <div class="login-container">
        <div class="login-logo-container">
            <img src="{% static 'images/logo.png' %}"/>
        </div>
        <form method="post">
            <div class="field">
                <h1> Login </h1>
            </div>
            
            {% csrf_token %}
             {% for field in form %} 
               <div class="field">
                    <p>{{field.label}}</p> 
                    <p>{{field}}</p>
               </div>
             {% endfor %}
             <p class="forgot"> <a href="">Forgot your password?</a></p>
            <div class="btns">
                <input type="submit" value="login" /> 
                <a href="{% url 'account:signup' %}"> sign up</a>
            </div>
            
            <div class="error_board">
                <p>{{error_msg}}</p>
            </div>
            <input type="hidden" name="next" value="{{request.GET.next}}"/>
        </form>
        
     </div>
{% endblock %}

templates/showprofile.html
{% extends 'base.html' %}  
{% load static %} 
{% block title %} 
     show profile
{% endblock %}
{% block css %} 
     <link rel="stylesheet" href="{% static 'editprofile.css' %}" />
{% endblock %}
{% block content %} 
    <section class="user-profile">
        <div class="profilePhoto">
            <div class="photo">
                <img src="{{user.profile.profile_photo.url}}"/>
            </div>
            {% for field in profile %} 
            <div class="field-label">
                <p class="input">{{field}}</p>
                <p class="label">{{field.label}}</p>
            </div>
         {% endfor %}
        </div>
        <div class="user">
            {% for field in userform %} 
              <div class="field-label">
                <p class="input">{{field}}</p>
                <p class="label">{{field.label}}</p>

              </div>
            {% endfor %}
          
        </div>
        <hr>
        <div class="download-books">
           <h3>You have downloaded {{user.download_books.count}} books</h3>
           <div class="books-grid">
               
            {% for book in d_book %}
                <div class="book">
                    <a href="{% url 'bookstore:book-detail' book.book.slug %}">
                       <img src="{{book.book.cover.url}}"  alt="{{book.title}}"/>
                    </a>
                    
               </div>

            {% endfor %}
           </div>
        </div>
        <div class="upload-books">
            <h3> You have uploaded {{blo}} books </h3>
            <div class="books-grid">
                {% for book in u_book %}
                 <div class="book">
                    <a href="{% url 'bookstore:book-detail' book.book.slug %}">
                        <img src="{{book.book.cover.url}}"/>
                     </a>
                     
                 </div>
                 {% endfor %}
            </div>
        </div>
    </section>
{% endblock %} 

templates/signup.html
{% extends 'base.html' %} 
{% load static %} 
{% block css %} 
    <link rel="stylesheet" href="{% static 'singup.css' %}"/>
{% endblock %}
{% block content %} 
    <section class="create-account-form">
          
          <div class="logo">
                
                <div class="img-div">
                    <img src="{% static 'images/logo.png' %}"/>
                </div>
             {% if new_user %} 

             {% else %}
              <div class="h1-div">
                   <h1> Create</h1>
                   <h1> Your Account</h1>
              </div>
            {% endif %} 
          </div>
        {% if new_user %} 
        <div>
          <h1 style="color:#343a40;width:70%;">  <span style="color:green"> {{new_user.username}} </span> you create your account successfully</h1>
          <p style="color:#343a40;width:70%;"> Now you can <a href="{% url 'account:login' %}">log in</a> to your account</p>
        </div>
        {% else %}
      
        <form action="." method="post">
            {% csrf_token %}

            {% for field in form %} 
                <p class="label">{{field.label}}</p>
                <div class="field">
                    <p class="input">{{field}}</p>
                    <p class="errors">{{field.errors}}</p>
                </div>
                
            {% endfor %}
            <div class="btns">
                <input type="submit" value ="create account" />
                <a href="{% url 'account:login' %}">
                  Already have account?
                </a>
            </div>
        </form>
        {% endif %} 
    </section>

{% endblock %}

templates/upload_book.html
{% extends 'base.html' %} 
{% load static %} 
{% block css %}
   <link rel="stylesheet" href="{% static 'upload.css' %}"/>
{% endblock %}
{% block content %} 
      <form method="post" enctype="multipart/form-data">
         {% csrf_token %}
         {{upload_form.as_p}} 
         <input type="submit" value="upload" />
         <p>{{upload_form.errors}}</p>
       </form>
     {% if b_exist %}
       <div>
            <img src="{{b_exist.book.cover.url}}" width="150px"/>
    
      </div>
      <p>This book is already uploaded!</p>
    {% endif %} 
{% endblock %}